require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-graphql

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.1
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/ExtractInputType:
  Enabled: false

GraphQL/ExtractType:
  Exclude:
    - 'app/graphql/**/base_*.rb'
    - 'app/graphql/types/mutation_type.rb'
    - 'app/graphql/types/query_type.rb'
    - 'app/graphql/types/festival_type.rb'

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 100
  AllowedPatterns: ['\A\s*#']

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
  Max: 10

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*'

Metrics/PerceivedComplexity:
  Enabled: false
  Max: 10

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/policies/**/*'

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleSubjects:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/RepeatedExample:
  Enabled: false

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
