require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-graphql

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.1
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

GraphQL/ExtractType:
  Exclude:
    - 'app/graphql/**/base_*.rb'
    - 'app/graphql/types/mutation_type.rb'
    - 'app/graphql/types/query_type.rb'

GraphQL/FieldDescription:
  Exclude:
    - 'app/graphql/**/base_*.rb'
    - 'app/graphql/types/mutation_type.rb'
    - 'app/graphql/types/query_type.rb'

GraphQL/ObjectDescription:
  Exclude:
    - 'app/graphql/nzif_schema.rb'
    - 'app/graphql/sources/**/*'
    - 'app/graphql/**/base_*'
    - 'app/graphql/types/query_type.rb'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 100
  AllowedPatterns: ['\A\s*#']

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - for
    - by

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleSubjects:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
