admin:
  description: Administrator
  implies:
    people:
      description: Manage people
      implies:
        permissions:
          description: Manage permissions
    activities:
      description: Manage activities
      implies:
        shows:
          description: Manage shows
        workshops:
          description: Manage workshops
        social_events:
          description: Manage social events
    registrations:
      description: Manage registrations
    content:
      description: Manage content
    payments:
      description: Manage payments
team_member:
  description: Team member
