roles:
  activities:
    show:
      activity:
        - director
      session:
        - host
        - performer
        - muso
        - operator
        - scorekeeper
    workshop:
      activity:
        - tutor
      session:
        - muso
        - support
    social_event:
      activity:
        - organiser
    conference:
      activity:
        - speaker
